feat: add additional display classes
cds-snc/gcds-utility pull request #191
Opened 2024-10-25 00:40 UTC by melaniebmn

# Summary | Résumé

Add additional display classes to provide further flexibility.

2024-10-25 12:35 UTC, ethanWallace requested changes
Looks good! Just one small thing

2024-10-25 12:35 UTC, ethanWallace commented on src/utilities/display.scss
> +  table-row	: table-row	,
Seems to be a couple extra spaces on this line

2024-10-25 15:33 UTC, daine commented on renovate.json
> +    "template": "{{version}}\n\nReleased on: {{date}}"
Can we move this to a separate PR so it's cleaner and easier to reference in the future? TY!

2024-10-28 16:19 UTC, daine approved these changes

2024-10-28 16:24 UTC, merged